server:
  port: 8980
#自定义配置
  app:
    name: tutorial
    port: 9098

spring:
  #数据库
  datasource:
    dynamic:
      primary: mysql
      strict: false
      datasource:
        mysql:
          url: jdbc:mysql://127.0.0.1:3306/db_example?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        clickhouse:
          url: jdbc:clickhouse://127.0.0.1:8123/example
          username: default
          password: admin@123456
          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password:
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


mybatis-plus:
  configuration:
    cache-enabled: false
    local-cache-scope: statement
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml


jwt:
  # 令牌自定义标识
  header: Authorization
  secret: Asdjsja@74673$$%
  expireTime: 600